# fly.toml app configuration file generated for openchesslab on 2026-09-25T11:10:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openchesslab'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  PHX_SERVER = 'true'
  PHX_HOST = 'openchesslab.fly.dev'
  DNS_CLUSTER_QUERY = 'openchesslab.internal'
  POSITION_STORE_OWNER = 'true'
  ANALYSIS_STORE_OWNER = 'true'
  POSITION_STORE_DIRECTORY = '/data/position-db'
  ANALYSIS_STORE_PATH = '/data/analysis-store.dets'
  POSITION_STORE_RECORDS_PER_SEGMENT = '1000000'
  POSITION_STORE_EXACT_BUCKET_COUNT = '1048576'
  POSITION_STORE_PROPERTY_BUCKET_COUNT = '65536'

[processes]
  app = "env POSITION_STORE_OWNER=true ANALYSIS_STORE_OWNER=true /app/bin/openchesslab start"
  replica = "env POSITION_STORE_OWNER=false ANALYSIS_STORE_OWNER=false /app/bin/openchesslab start"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app', 'replica']
  
[[http_service.checks]]
  grace_period = "5s"
  interval = "15s"
  method = "GET"
  timeout = "2s"
  path = "/health"

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  timeout = "2s"
  path = "/ready"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "position_db"
  destination = "/data"
  processes = ["app"]
